### ISSUE TITLE
Topic not found topic_name for cluster

### ISSUE THREAD

**Issue by rsurendra** [yahoo/kafka-manager#181]
Created a new kafka topic with 8 partitions and 3 replicas using Kafka Manager and after filling the queue with 2.6 million messages deleted it. Kafka Manager deleted it successfully. And then i tried to create the same topic_name with 1 partition and 1 replica, kafka manager created the topic, but when you click on the topic, it does not exist... In the list, it shows the topic with blank count for brokers, broker %, partitions, replicas etc. Not able to delete this topic bcoz it does not exist. Not able to create a new one, coz it already exists in the list...

**Comment by patelh** [comment]
This should be fixed in 1.3.0.4.

**Comment by rsurendra** [comment]
@patelh : Thanks for the info... Updated to 1.3.0.4 as recommended... But the issue still persists... now the topics are indicated by pink color that the topic you have deleted is not yet deleted.

**Comment by olehko** [comment]
Have the same issue - some topics don't work and can't be deleted through Kafka manager. Deleting the topic via zookeeper helped for the first time, but now it doesn't. After that I tried deleting topic logs directly from the file system - that helped for a couple of times, but not anymore. Now there are topics which still don't work even after deleting them in zookeeper and removing logs from the disk and re-creating the topic in Kafka manager.

**Comment by abhinavddr** [comment]
Hello, I am using Kafka 0.8.2.1.  I was able to get rid of the topic on Kafka Manager by deleting the znode of deleted topic in zookeeper.
